"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
*!
Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2025)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DownloadButton(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    LABEL_FIELD_NUMBER: builtins.int
    DEFAULT_FIELD_NUMBER: builtins.int
    HELP_FIELD_NUMBER: builtins.int
    FORM_ID_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    DISABLED_FIELD_NUMBER: builtins.int
    USE_CONTAINER_WIDTH_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    ICON_FIELD_NUMBER: builtins.int
    IGNORE_RERUN_FIELD_NUMBER: builtins.int
    DEFERRED_FILE_ID_FIELD_NUMBER: builtins.int
    SHORTCUT_FIELD_NUMBER: builtins.int
    id: builtins.str
    label: builtins.str
    default: builtins.bool
    help: builtins.str
    form_id: builtins.str
    url: builtins.str
    disabled: builtins.bool
    use_container_width: builtins.bool
    type: builtins.str
    icon: builtins.str
    ignore_rerun: builtins.bool
    deferred_file_id: builtins.str
    shortcut: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        label: builtins.str = ...,
        default: builtins.bool = ...,
        help: builtins.str = ...,
        form_id: builtins.str = ...,
        url: builtins.str = ...,
        disabled: builtins.bool = ...,
        use_container_width: builtins.bool = ...,
        type: builtins.str = ...,
        icon: builtins.str = ...,
        ignore_rerun: builtins.bool = ...,
        deferred_file_id: builtins.str | None = ...,
        shortcut: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_deferred_file_id", b"_deferred_file_id", "deferred_file_id", b"deferred_file_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_deferred_file_id", b"_deferred_file_id", "default", b"default", "deferred_file_id", b"deferred_file_id", "disabled", b"disabled", "form_id", b"form_id", "help", b"help", "icon", b"icon", "id", b"id", "ignore_rerun", b"ignore_rerun", "label", b"label", "shortcut", b"shortcut", "type", b"type", "url", b"url", "use_container_width", b"use_container_width"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_deferred_file_id", b"_deferred_file_id"]) -> typing.Literal["deferred_file_id"] | None: ...

Global___DownloadButton: typing_extensions.TypeAlias = DownloadButton
