"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
*!
Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2025)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class TextAlignmentConfig(google.protobuf.message.Message):
    """Text alignment configuration for text elements"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Alignment:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _AlignmentEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TextAlignmentConfig._Alignment.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNSPECIFIED: TextAlignmentConfig._Alignment.ValueType  # 0
        LEFT: TextAlignmentConfig._Alignment.ValueType  # 1
        CENTER: TextAlignmentConfig._Alignment.ValueType  # 2
        RIGHT: TextAlignmentConfig._Alignment.ValueType  # 3
        JUSTIFY: TextAlignmentConfig._Alignment.ValueType  # 4

    class Alignment(_Alignment, metaclass=_AlignmentEnumTypeWrapper): ...
    UNSPECIFIED: TextAlignmentConfig.Alignment.ValueType  # 0
    LEFT: TextAlignmentConfig.Alignment.ValueType  # 1
    CENTER: TextAlignmentConfig.Alignment.ValueType  # 2
    RIGHT: TextAlignmentConfig.Alignment.ValueType  # 3
    JUSTIFY: TextAlignmentConfig.Alignment.ValueType  # 4

    ALIGNMENT_FIELD_NUMBER: builtins.int
    alignment: Global___TextAlignmentConfig.Alignment.ValueType
    def __init__(
        self,
        *,
        alignment: Global___TextAlignmentConfig.Alignment.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["alignment", b"alignment"]) -> None: ...

Global___TextAlignmentConfig: typing_extensions.TypeAlias = TextAlignmentConfig
