"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
*!
Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2025)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Toast(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BODY_FIELD_NUMBER: builtins.int
    ICON_FIELD_NUMBER: builtins.int
    DURATION_FIELD_NUMBER: builtins.int
    body: builtins.str
    """Display message"""
    icon: builtins.str
    """Emoji"""
    duration: builtins.int
    """The time to display the toast message in seconds.
    If not set, the toast will be displayed for 4 seconds. A value of 0
    indicates that the toast should not be automatically dismissed.
    """
    def __init__(
        self,
        *,
        body: builtins.str = ...,
        icon: builtins.str = ...,
        duration: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_duration", b"_duration", "duration", b"duration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_duration", b"_duration", "body", b"body", "duration", b"duration", "icon", b"icon"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_duration", b"_duration"]) -> typing.Literal["duration"] | None: ...

Global___Toast: typing_extensions.TypeAlias = Toast
