name: continuous-integration

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # Latest pyOpenMS supports Python 3.9, 3.10, and 3.11
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --index-url https://pypi.cs.uni-tuebingen.de/simple/ pyopenms
        pip install -r requirements.txt -r requirements-dev.txt -r requirements-optional.txt
    - name: Test
      run: |
        python -m pytest --snapshot-warn-unused test/ # do not fail if unused snapshot, just warn
